L_arm_controller:
  L_shoulder_pan_joint:
    type: velocity_controllers/JointVelocityController
    joint: L_shoulder_pan_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  L_shoulder_lift_joint:
    type: velocity_controllers/JointVelocityController
    joint: L_shoulder_lift_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  L_elbow_joint:
    type: velocity_controllers/JointVelocityController
    joint: L_elbow_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  L_wrist_1_joint:
    type: velocity_controllers/JointVelocityController
    joint: L_wrist_1_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  L_wrist_2_joint:
    type: velocity_controllers/JointVelocityController
    joint: L_wrist_2_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  L_wrist_3_joint:
    type: velocity_controllers/JointVelocityController
    joint: L_wrist_3_joint
    pid: {p: 10.0, i: 0, d: 100.0}

R_arm_controller:
  R_shoulder_pan_joint:
    type: velocity_controllers/JointVelocityController
    joint: R_shoulder_pan_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  R_shoulder_lift_joint:
    type: velocity_controllers/JointVelocityController
    joint: R_shoulder_lift_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  R_elbow_joint:
    type: velocity_controllers/JointVelocityController
    joint: R_elbow_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  R_wrist_1_joint:
    type: velocity_controllers/JointVelocityController
    joint: R_wrist_1_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  R_wrist_2_joint:
    type: velocity_controllers/JointVelocityController
    joint: R_wrist_2_joint
    pid: {p: 10.0, i: 0, d: 100.0}
  R_wrist_3_joint:
    type: velocity_controllers/JointVelocityController
    joint: R_wrist_3_joint
    pid: {p: 10.0, i: 0, d: 100.0}
